"use client";

import { useState } from "react";
import { useTranslation } from "react-i18next";
import { BiLinkExternal, BiPencil, BiPlus, BiTrash, BiX } from "react-icons/bi";
import { BsCheckCircleFill, BsCircle } from "react-icons/bs";
import PageBreadcrumb from "@/components/common/PageBreadcrumb";
import DateTimePicker from "@/components/datetime/DateTimePicker";
import DeleteConfirmModal from "@/components/modal/DeleteConfirmModal";
import LeadTimeSelect from "@/components/notifications/LeadTimeSelect";
import { useCreateLearningItem, useCreateLearningTopic, useDeleteLearningItem, useDeleteLearningTopic, useLearningTopics, useToggleLearningItem, useUpdateLearningItem, useUpdateLearningTopic } from "@/hooks/useLearning";
import { alertStore } from "@/stores/alert-store";
import { LearningItemRequest, LearningItemResponse, LearningTopicRequest, LearningTopicResponse } from "@/types/learning/learning";
import { parseAxiosError } from "@/utils/handleError";
import { formatDateTime } from "@/utils/i18n-date";

export default function LearningPage() {
  const { t } = useTranslation(); const showAlert = alertStore((s) => s.show);
  const { data, isLoading, isError, refetch } = useLearningTopics();
  const [editingTopic, setEditingTopic] = useState<LearningTopicResponse | null | undefined>();
  const [editingItem, setEditingItem] = useState<LearningItemResponse | null>(null);
  const topics = data ?? [];
  return <div className="space-y-6">
    <PageBreadcrumb pageTitle={t("learning.title", "Learning")} kicker={t("learning.kicker", "Learning tracker")} flourish={t("learning.flourish", "curiosity")} />
    <div className="flex flex-wrap items-center justify-between gap-3"><p className="max-w-xl text-sm text-gray-600 dark:text-gray-300">{t("learning.intro", "Track what you are learning, one item at a time.")}</p><button type="button" onClick={() => setEditingTopic(null)} className="husrev-btn"><BiPlus className="h-4 w-4" />{t("learning.newTopic", "New topic")}</button></div>
    {isError && <div className="flex items-center justify-between gap-3 rounded-2xl ring-1 ring-husrev-sand bg-white px-4 py-3 text-sm text-error-500 dark:bg-husrev-shadow dark:ring-white/[0.06]"><span>{t("learning.error", "Topics could not be loaded.")}</span><button type="button" onClick={() => refetch()} className="rounded px-2 py-1 text-xs text-husrev-ember hover:underline">{t("common.retry", "Retry")}</button></div>}
    {isLoading && <div className="space-y-3">{[0, 1, 2].map((i) => <div key={i} className="h-28 rounded-2xl bg-husrev-sand/40 motion-safe:animate-pulse motion-reduce:opacity-50" />)}</div>}
    {!isLoading && !isError && !topics.length && <div className="rounded-2xl ring-1 ring-husrev-sand bg-white px-6 py-12 text-center shadow-card-warm dark:bg-husrev-shadow dark:ring-white/[0.06]"><div className="husrev-kicker text-husrev-amber">{t("learning.empty.kicker", "Your learning list is empty")}</div><p className="mx-auto mt-1 max-w-md text-sm text-gray-500 dark:text-gray-400">{t("learning.empty.body", "Create a topic and begin collecting the things you want to master.")}</p><button type="button" onClick={() => setEditingTopic(null)} className="husrev-btn mt-5">{t("learning.newTopic", "New topic")}</button></div>}
    <div className="space-y-3">{topics.map((topic) => <TopicCard key={topic.id} topic={topic} onEdit={() => setEditingTopic(topic)} onEditItem={setEditingItem} showAlert={showAlert} />)}</div>
    {editingTopic !== undefined && <TopicModal initial={editingTopic} onClose={() => setEditingTopic(undefined)} showAlert={showAlert} />}
    {editingItem && <ItemModal initial={editingItem} onClose={() => setEditingItem(null)} showAlert={showAlert} />}
  </div>;
}

function TopicCard({ topic, onEdit, onEditItem, showAlert }: { topic: LearningTopicResponse; onEdit: () => void; onEditItem: (i: LearningItemResponse) => void; showAlert: ReturnType<typeof alertStore.getState>["show"]; }) {
  const { t } = useTranslation(); const create = useCreateLearningItem(); const remove = useDeleteLearningItem(); const toggle = useToggleLearningItem(); const [text, setText] = useState("");
  const pct = topic.itemCount ? Math.round((topic.completedCount / topic.itemCount) * 100) : 0;
  const run = async (work: () => Promise<unknown>) => { try { await work(); } catch (err) { const { title, message } = parseAxiosError(err); showAlert({ title, message, type: "error", position: "top-center" }); } };
  return <div className="group relative overflow-hidden rounded-2xl bg-white shadow-card-warm ring-1 ring-husrev-amber/30 dark:bg-husrev-shadow"><span className="absolute inset-y-0 left-0 w-[4px] bg-husrev-amber" /><div className="pl-5 pr-3 py-4"><div className="flex items-start justify-between gap-3"><button type="button" onClick={onEdit} className="min-w-0 text-left"><h3 className="text-lg font-semibold tracking-tight text-husrev-ink dark:text-husrev-cream">{topic.title}</h3>{topic.description && <p className="mt-1 text-sm text-gray-500 dark:text-gray-400">{topic.description}</p>}</button><button type="button" onClick={onEdit} aria-label={t("common.edit", "Edit")} className="rounded p-1 text-gray-400 opacity-0 transition hover:text-husrev-ember group-hover:opacity-100"><BiPencil className="h-4 w-4" /></button></div><div className="mt-3 flex items-center gap-3"><div className="h-1.5 w-full overflow-hidden rounded-full bg-husrev-sand/40"><div className="h-full rounded-full bg-husrev-amber transition-all" style={{ width: `${pct}%` }} /></div><span className="whitespace-nowrap text-xs text-gray-500">{t("learning.progress", { done: topic.completedCount, total: topic.itemCount })}</span></div>
    <ul className="mt-3 space-y-1">{topic.items.map((item) => <li key={item.id} className="group/item flex items-start gap-2 rounded-lg px-2 py-1 text-sm hover:bg-husrev-cream/60 dark:hover:bg-white/[0.04]"><button type="button" onClick={() => void run(() => toggle.mutateAsync(item.id))} className="mt-0.5 shrink-0 text-gray-400 transition hover:text-brand-500" aria-label={item.completedAt ? t("learning.toggle.incomplete") : t("learning.toggle.complete")}>{item.completedAt ? <BsCheckCircleFill size={20} className="text-brand-500" /> : <BsCircle size={20} />}</button><button type="button" onClick={() => onEditItem(item)} className={`min-w-0 flex-1 text-left ${item.completedAt ? "line-through text-gray-400 dark:text-gray-500" : "text-gray-800 dark:text-white/90"}`}><span className="block truncate">{item.text}</span>{(item.url || item.estimatedMinutes !== null || item.reviewAt) && <span className="mt-0.5 flex flex-wrap gap-x-2 text-xs text-gray-400 no-underline">{item.url && <span className="inline-flex items-center gap-1"><BiLinkExternal />{new URL(item.url).hostname || "Link"}</span>}{item.estimatedMinutes !== null && <span>◷ {item.estimatedMinutes} dk</span>}{item.reviewAt && <span>{formatDateTime(item.reviewAt, { day: "numeric", month: "short", hour: "2-digit", minute: "2-digit" })}</span>}</span>}</button><button type="button" onClick={() => void run(() => remove.mutateAsync(item.id))} aria-label={t("common.delete", "Delete")} className="mt-0.5 shrink-0 rounded p-0.5 text-gray-400 opacity-0 transition hover:text-error-500 group-hover/item:opacity-100"><BiX className="h-4 w-4" /></button></li>)}</ul>
    <div className="mt-2 flex items-center gap-2 pl-2"><input value={text} onChange={(e) => setText(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter") { e.preventDefault(); void run(async () => { await create.mutateAsync({ topicId: topic.id, body: { text: text.trim() } }); setText(""); }); } }} maxLength={300} placeholder={t("learning.addItem", "Add item…")} className="husrev-input h-9 flex-1 text-sm" /><button type="button" disabled={!text.trim() || create.isPending} onClick={() => void run(async () => { await create.mutateAsync({ topicId: topic.id, body: { text: text.trim() } }); setText(""); })} className="husrev-btn-ghost h-9 px-3 text-sm"><BiPlus className="h-4 w-4" /></button></div></div></div>;
}

function TopicModal({ initial, onClose, showAlert }: { initial: LearningTopicResponse | null; onClose: () => void; showAlert: ReturnType<typeof alertStore.getState>["show"]; }) { const { t } = useTranslation(); const create = useCreateLearningTopic(); const update = useUpdateLearningTopic(); const remove = useDeleteLearningTopic(); const [title, setTitle] = useState(initial?.title ?? ""); const [description, setDescription] = useState(initial?.description ?? ""); const [confirming, setConfirming] = useState(false); const submit = async (e: React.FormEvent) => { e.preventDefault(); try { const body: LearningTopicRequest = { title: title.trim(), description: description.trim() || null }; if (initial) { await update.mutateAsync({ id: initial.id, body }); } else { await create.mutateAsync(body); } onClose(); } catch (err) { const x = parseAxiosError(err); showAlert({ ...x, type: "error", position: "top-center" }); } }; return <Modal onClose={onClose}><form onSubmit={submit}><ModalTitle kicker={initial ? t("learning.modal.editKicker") : t("learning.modal.newKicker")} title={initial ? t("learning.modal.editTitle") : t("learning.modal.createTitle")} /><div className="mt-6 space-y-4"><Field label={t("learning.field.title")}><input required autoFocus maxLength={160} value={title} onChange={(e) => setTitle(e.target.value)} className="husrev-input" placeholder={t("learning.placeholders.title")} /></Field><Field label={t("learning.field.description")}><textarea rows={3} value={description} onChange={(e) => setDescription(e.target.value)} className="husrev-input resize-none" placeholder={t("learning.placeholders.description")} /></Field></div><Actions onClose={onClose} pending={create.isPending || update.isPending || remove.isPending} />{initial && <button type="button" onClick={() => setConfirming(true)} className="mt-4 text-sm text-error-500 hover:underline"><BiTrash className="mr-1 inline" />{t("common.delete", "Delete")}</button>}</form><DeleteConfirmModal isOpen={confirming} onClose={() => setConfirming(false)} onConfirm={async () => { if (!initial) return; await remove.mutateAsync(initial.id); onClose(); }} isPending={remove.isPending} title={t("learning.confirmDeleteTitle")} message={t("learning.confirmDeleteTopic")} /></Modal>; }

function ItemModal({ initial, onClose, showAlert }: { initial: LearningItemResponse; onClose: () => void; showAlert: ReturnType<typeof alertStore.getState>["show"]; }) { const { t } = useTranslation(); const update = useUpdateLearningItem(); const [text, setText] = useState(initial.text); const [url, setUrl] = useState(initial.url ?? ""); const [notes, setNotes] = useState(initial.notes ?? ""); const [minutes, setMinutes] = useState(initial.estimatedMinutes?.toString() ?? ""); const [reviewAt, setReviewAt] = useState<string | null>(initial.reviewAt); const [lead, setLead] = useState<number | null>(initial.notifyMinutesBefore); const submit = async (e: React.FormEvent) => { e.preventDefault(); try { const body: LearningItemRequest = { text: text.trim(), url: url.trim() || null, notes: notes.trim() || null, estimatedMinutes: minutes === "" ? null : Number(minutes), reviewAt, notifyMinutesBefore: lead }; await update.mutateAsync({ id: initial.id, body }); onClose(); } catch (err) { const x = parseAxiosError(err); showAlert({ ...x, type: "error", position: "top-center" }); } }; return <Modal onClose={onClose}><form onSubmit={submit}><ModalTitle kicker={t("learning.modal.editKicker")} title={t("learning.modal.itemEditTitle")} /><div className="mt-6 space-y-4"><Field label={t("learning.field.itemText")}><input required autoFocus maxLength={300} value={text} onChange={(e) => setText(e.target.value)} className="husrev-input" /></Field><Field label={t("learning.field.url")}><input type="url" maxLength={512} value={url} onChange={(e) => setUrl(e.target.value)} className="husrev-input" /></Field><Field label={t("learning.field.notes")}><textarea rows={3} value={notes} onChange={(e) => setNotes(e.target.value)} className="husrev-input resize-none" /></Field><Field label={t("learning.field.estimatedMinutes")}><input type="number" min="0" value={minutes} onChange={(e) => setMinutes(e.target.value)} className="husrev-input" /></Field><Field label={t("learning.field.reviewAt")}><DateTimePicker value={reviewAt} onChange={setReviewAt} /></Field><LeadTimeSelect value={lead} onChange={setLead} disabled={!reviewAt} /></div><Actions onClose={onClose} pending={update.isPending} /></form></Modal>; }
function Modal({ children, onClose }: { children: React.ReactNode; onClose: () => void }) { return <div className="fixed inset-0 z-[100000] flex items-center justify-center bg-husrev-ink/40 p-4 backdrop-blur-sm" onClick={onClose}><div onClick={(e) => e.stopPropagation()} className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-3xl husrev-modal grain p-5 sm:p-7 husrev-settle">{children}</div></div>; }
function ModalTitle({ kicker, title }: { kicker: string; title: string }) { return <div><span className="husrev-kicker text-husrev-ember/80 dark:text-husrev-amber/80">{kicker}</span><h3 className="mt-1 text-2xl font-semibold tracking-tight text-husrev-ink dark:text-husrev-cream">{title}</h3></div>; }
function Actions({ onClose, pending }: { onClose: () => void; pending: boolean }) { const { t } = useTranslation(); return <div className="mt-6 flex justify-end gap-2"><button type="button" onClick={onClose} disabled={pending} className="husrev-btn-ghost">{t("common.cancel", "Cancel")}</button><button type="submit" disabled={pending} className="husrev-btn">{pending ? t("common.saving", "Saving…") : t("common.save", "Save")}</button></div>; }
function Field({ label, children }: { label: React.ReactNode; children: React.ReactNode }) { return <label className="block space-y-1.5"><span className="husrev-kicker text-gray-600 dark:text-gray-300">{label}</span>{children}</label>; }
